tap "guardian/homebrew-devtools"
tap "caskroom/versions"

brew "ssm"
cask "keepassx"
cask "intellij-idea"
cask "google-chat"
cask "google-backup-and-sync"
cask "iterm2"
brew "awscli"
cask "android-sdk"
cask "android-ndk"
brew "jq"
cask "java8"
brew "sbt@1"
cask "adobe-acrobat-reader"
